if (PBC_INCLUDE_DIRS AND PBC_LIBRARIES)
  set(PBC_FIND_QUIETLY TRUE)
endif ()

find_path(PBC_INCLUDE_DIRS NAMES pbc/pbc.h)
find_library(PBC_LIBRARIES NAMES pbc libpbc)

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(PBC DEFAULT_MSG PBC_INCLUDE_DIRS PBC_LIBRARIES)

mark_as_advanced(PBC_INCLUDE_DIRS PBC_LIBRARIES)
